server.port: 8080

basePathForYamls: "/Users/jae.park/work/src/github.com/jaekwon.park/petstore/server/petstore-api-microservice/yamls"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
